# Generated by Django 3.2 on 2021-07-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210705_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='nick_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
